### ISSUE TITLE
#TODO Revert String too long Error

### ISSUE THREAD

**Issue by Joshua-Nathanael** [EE4032Project/OverPass#15]
![Screenshot 2022-10-31 23:53:09](https://user-images.githubusercontent.com/48911477/199051628-4957d14a-d2ab-4a21-9d85-9c526d8533f3.png)
Recreate: 
Ubuntu Terminal
Terminal 1: 
./start_gananche_testnet 10 
Terminal 2: 
python3 demo.py LCSOverPass
...
time_to_delegate: 100

**Comment by Ch40gRv1-Mu** [comment]
Resolved by https://github.com/EE4032Project/OverPass/pull/18
